spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 22@pwds
    url: jdbc:mysql://localhost:3306/apicrud?createDatabaseIfNotExist=true
    username: antonio
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true